apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: app01
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer